/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary:                    'var(--md-sys-color-primary)',
        'on-primary':               'var(--md-sys-color-on-primary)',
        'primary-container':        'var(--md-sys-color-primary-container)',
        'on-primary-container':     'var(--md-sys-color-on-primary-container)',
        secondary:                  'var(--md-sys-color-secondary)',
        'on-secondary':             'var(--md-sys-color-on-secondary)',
        'secondary-container':      'var(--md-sys-color-secondary-container)',
        'on-secondary-container':   'var(--md-sys-color-on-secondary-container)',
        tertiary:                   'var(--md-sys-color-tertiary)',
        'on-tertiary':              'var(--md-sys-color-on-tertiary)',
        'tertiary-container':       'var(--md-sys-color-tertiary-container)',
        'on-tertiary-container':    'var(--md-sys-color-on-tertiary-container)',
        error:                      'var(--md-sys-color-error)',
        'on-error':                 'var(--md-sys-color-on-error)',
        'error-container':          'var(--md-sys-color-error-container)',
        'on-error-container':       'var(--md-sys-color-on-error-container)',
        warning:                    'var(--md-sys-color-warning)',
        'on-warning':               'var(--md-sys-color-on-warning)',
        'warning-container':        'var(--md-sys-color-warning-container)',
        'on-warning-container':     'var(--md-sys-color-on-warning-container)',
        success:                    'var(--md-sys-color-success)',
        'on-success':               'var(--md-sys-color-on-success)',
        'success-container':        'var(--md-sys-color-success-container)',
        'on-success-container':     'var(--md-sys-color-on-success-container)',
        surface:                    'var(--md-sys-color-surface)',
        'on-surface':               'var(--md-sys-color-on-surface)',
        'surface-variant':          'var(--md-sys-color-surface-variant)',
        'on-surface-variant':       'var(--md-sys-color-on-surface-variant)',
        'surface-container-lowest': 'var(--md-sys-color-surface-container-lowest)',
        'surface-container-low':    'var(--md-sys-color-surface-container-low)',
        'surface-container':        'var(--md-sys-color-surface-container)',
        'surface-container-high':   'var(--md-sys-color-surface-container-high)',
        'surface-container-highest':'var(--md-sys-color-surface-container-highest)',
        outline:                    'var(--md-sys-color-outline)',
        'outline-variant':          'var(--md-sys-color-outline-variant)',
        'inverse-surface':          'var(--md-sys-color-inverse-surface)',
        'inverse-on-surface':       'var(--md-sys-color-inverse-on-surface)',
        'inverse-primary':          'var(--md-sys-color-inverse-primary)',
        background:                 'var(--md-sys-color-background)',
        'on-background':            'var(--md-sys-color-on-background)',
      },
      borderRadius: {
        'shape-xs':   'var(--md-sys-shape-corner-extra-small)',
        'shape-sm':   'var(--md-sys-shape-corner-small)',
        'shape-md':   'var(--md-sys-shape-corner-medium)',
        'shape-lg':   'var(--md-sys-shape-corner-large)',
        'shape-xl':   'var(--md-sys-shape-corner-extra-large)',
        'shape-full': 'var(--md-sys-shape-corner-full)',
      },
      fontFamily: {
        sans: ['Roboto', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg':  ['57px', { lineHeight: '64px', letterSpacing: '-0.25px' }],
        'display-md':  ['45px', { lineHeight: '52px', letterSpacing: '0' }],
        'display-sm':  ['36px', { lineHeight: '44px', letterSpacing: '0' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '0' }],
        'headline-sm': ['24px', { lineHeight: '32px', letterSpacing: '0' }],
        'title-lg':    ['22px', { lineHeight: '28px', letterSpacing: '0' }],
        'title-md':    ['16px', { lineHeight: '24px', letterSpacing: '0.15px' }],
        'title-sm':    ['14px', { lineHeight: '20px', letterSpacing: '0.1px' }],
        'body-lg':     ['16px', { lineHeight: '24px', letterSpacing: '0.5px' }],
        'body-md':     ['14px', { lineHeight: '20px', letterSpacing: '0.25px' }],
        'body-sm':     ['12px', { lineHeight: '16px', letterSpacing: '0.4px' }],
        'label-lg':    ['14px', { lineHeight: '20px', letterSpacing: '0.1px' }],
        'label-md':    ['12px', { lineHeight: '16px', letterSpacing: '0.5px' }],
        'label-sm':    ['11px', { lineHeight: '16px', letterSpacing: '0.5px' }],
      },
    },
  },
  plugins: [],
};
